### ISSUE TITLE
FR: Do not stretch image in modal dialog

### ISSUE THREAD

**Issue by amedvedjev** [Evilweed/protractor-beautiful-reporter#57]
When we open image in modal dialog it is stretched.
It will be nice to center image and to set:
```
max-width: 100%;
max-height: 100%;
```

**Comment by pederjohn** [comment]
I would like that too!

**Comment by miller45** [comment]
@amedvedjev @pederjohn actually you can do that already by yourselfes:
add 
```css
.screenshotImage{
  display:block;
  width:50%;
  margin-left:auto;
  margin-right:auto;
}
```
